---
title: "First Knit"
author: "Estrella Aguilar"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended high school at antelope valley high school here in Lancaster. I graduated valedictorian with a 4.1 GPA last year. I think English is easier for me than math but it depends on the teacher. I did best in my Spanish class because the work was very easy and the teacher taught well. I also did the best in English, even though the class was very hard which was an AP honors class it helped me a lot now that I am attending college. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I am currently using an HP chrome book.On a scale from 1 to 10 I would rate myself about a 7.5 on knowing computer stuff. I have good internet access where I live, it usually always runs fast.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I prefer to be called star which is my nickname.Estrella translates to star in Spanish.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   My main goal in life is to become a lawyer and earn lots of money. College subjects I think would be of the greatest interest to me is political science which is my current major and the most popular major to transfer into law. I want to earn a degree in law at UCLA.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I recently went to a foreign country for the first time ever which was Mexico. I would like to go to Greece one day in the future if I can. I have not been in the military but if I could choose a branch to get drafted in I would choose the marines because my ex went to the marines and they can keep me safe, the marines also looks interesting because I can visit the sea.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   This math 116 class is the first class I have taken here in college. I need to take this class to be able to go to UCLA which is my dream school!The grade I need to attain in stats to not upset my future plans is an A. My plan is to work hard and try my best.
 






  




